### ISSUE TITLE
SVN 관련 설명 세션 준비

### ISSUE THREAD

**Issue by dahyeong-yun** [ta9-kr/tutorial-newcomer#1]
- [x] 목차 생성
- [x] 발표 세션 준비(10~15 min)
  - [x] 스크립트(=대본) 준비
    - [x] 시연 플로우 자료(기록)로 준비할 것
- [x] 완성본 wiki에 등록해 둘 것
- (optional) 예상 질문 및 답변 -> 소프트 스킬
  - 예시
    - SVN 왜 써요?
    - SVN 써요? 실제 프로젝트에서 어떻게 쓰죠?
    - (나는 이 발표를 무슨 목적으로 하고 있는지 -> **프로젝트의 원활한 진행을 위해서**)

**Comment by dahyeong-yun** [comment]
1) svn 주소랑 계정 비번 

2) IDE svn 설정하고 체크아웃 하고 변경사항 커밋
- 커밋 메세지
- 커밋
- 스프링 프로젝트에서 커밋하면 안되는 파일 -> ide setting 
  - eclipse -> .project, .classpath .settings/
  - inteillj -> .idea/
  - 빌드 파일 올리지 말아라 -> .class -> /target/* , 라이브러리 -> User/사용자명/.m2/
     *Controller.java -> 실행되나?
     *Controller.class

3) 
-> 커밋하기 전에 업데이트 꼭 받으라 왜?
- pom.xml -> maven 설정
+ IDE checkout a          파일 수정 1 커밋 a.txt
+ tortiseSVN  checkout  파일 수정 업데이트 안받고 수정 커밋 a.txt

**Comment by DONGRYULOH** [comment]
[SVN최종본.zip](https://github.com/ta9-kr/tutorial-newcomer/files/6837337/SVN.zip)

**Comment by DONGRYULOH** [comment]
[SVN최종본.zip](https://github.com/ta9-kr/tutorial-newcomer/files/6837344/SVN.zip)
